### ISSUE TITLE
Request Tambahan

### ISSUE THREAD

**Issue by ardhaps** [isfaaghyth/Buku-Android#1]
Untuk Intermediate, mungkin bisa ditambahkan:
- Broadcast Receiver
- Content Provider (kegunaan, mengakses CP apps lain, maupun membuat CP sendiri)
- Firebase (Storage & Notifications)
- MVVM mungkin jangan dulu (biar fokus ke MVP)
- Project ditambahkan modul Login
- Dependency Injection (Library Dagger)

Untuk Beginner, mungkin ditambahkan:
- Pengenalan XML (syntax-syntax yang sering dipakai)
- Coordinator Layout
- Sekilas Android Material
- View Injection (Library ButterKnife)

**Comment by isfaaghyth** [comment]
siap, terima kasih :)
siap ditambahkan Dependency Injection, untuk yang lainnya sudah ada di daftar isi :)
Di Beginner siap ditambahkan View Injection, untuk yang lainnya sudah ada di daftar isi :)

**Comment by isfaaghyth** [comment]
close

**Comment by isfaaghyth** [comment]
close #e891c0da08dd6633f02776de4f2aed28749556b8
